language: python

python:
- '3.5'

env:
  global:
    - VERSION_BASE='2016.12'

install:
  - pip install codeclimate-test-reporter 2> /dev/null
  - export VERSION="${VERSION_BASE}.${TRAVIS_BUILD_NUMBER}"
  - if [ "$TRAVIS_TAG" != '' ]; then export VERSION="$TRAVIS_TAG"; fi
  - sed -i -e "s/dynamic-dev/${VERSION}/g" setup.py
  - pip install .

script:
  - nosetests --with-coverage --cover-erase --cover-package=framepy
  - bash ./smoke-tests/run.sh || exit 1

after_script:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then codeclimate-test-reporter --token ae118fd81fc349130263713e74be974b318b2b9f25785711ad0aa8f4fd061576; fi
  - if [ "$TRAVIS_BRANCH" == "release" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git tag ${VERSION}; git push --tags -q https://mkorman9:${GITHUB_TOKEN}@github.com/mkorman9/framepy; fi

deploy:
  provider: pypi
  user:
    secure: Rvn9YH2D03IvfgY95pBbwsdy6rZIapfGEDwM5q2YCflgarUpMyyYUXv3q//UmTh1JSsM/QpYYvzO5Fm9TM38AkzRWLh3CJGiwBYcRmE3+CG5tmD5r3TNsrfkj4jqNW2THxMS6wi5w137pl+cygd4PfmbRAFqQqgQWuA8+Ai80lKJ6WkP7ezOgYOJ8lW97iMf7CecMDcZZ3iqCZBjbc2EaMO+Bz7biZ9c7/VoUcdsGageC/FheYa0YjtwiuQlvs43uJ59OCEeNMeFJuiI5/b7MtNX4Nj6Z1iVUvXV3kOjbULmbwIo90roP9V8P7BCt54BrR9KLd38On8J1KboKvXd5lQvB3ZDnzBsUhUd9Lary0Fi/gwP0HRQVzH+H8gt4E1Cudcq55/SLb9O/KrnuUy6LEiWt/hQ0EbBzHfPIVM2XQW5kt7rGYC3mJJQYIi53qbp0ysHQuzFuY8Iu2OCHWZr58ZeE9MRTS97iRoqrc0NFrnwD1KhaoWHCG/yUW3h0uri8Gcp+PHchA4venOjTULPXontXI7oG+0YQ/UfW5Pp7JP5N2XcNhYqX4B70kenewIamuWPTILAg5QV8uANE4N9RE12aAdic7uftuLO+XykJaAwS+EuT8eyRkiUn5IYimsBYqM/6mwM+J54hs8MUoy2tW7+5FnTxmf6FLnWdnGtCj8=
  password:
    secure: I9U2UctzIE11ksmGM8oTPs6Ng9B30bIHCKHpabt12c+buxlv4qOTfigdPN9GqJFs5noGx6Jal4l0aBkJPRKw7V0JAaokwP8jDIP39UW33MzzznM6FYVLFLQgwLuHyt5Y/7iVorB47HJF+7MNvtE28USOcoOOZUK4cdLjLI071NEApC1zUihyl7JmfhJzwK97kzuBWagBPPf58JIhN0O8XiJa4og0zAm2xnhdQDxssTkfwRWA35ZG0shfKflrwi7w12A3dryANnUli2/rum2Vdyu7nRQ5x0WRuGhvLNZhqaJQdmOqkjqPdfiqsIU057hxVlOpXO3/qCShgkT8fsWe16AEw5JkQVGe165zgxRRgACBerpWbU8VnJUkRbcMy87i/GIlxVS+QSsuTqWvtJSwSAuNAOzJ4qXPg9TUeRIBv/KeW8YEnd8g18xdmUXi0k84qPB8ZFXjeqZJalMLP6SRpDxDr59hf8PwfTde0rihOjPCAZ/R1kqLgR/OmzKPZETaP/RKcuZh/tstv5yxAiXdm4Qrm1uwGMElbA742U0jHtcNB9881U033FihxJtNNwbDAWG0um2ZdOcK3b4c1VeliMTH2Cx44tmfKQhVSY1Ju5quyVH0GgKP4w8CmGGOgrRREtdsoSkexs9ZWO+TdptDcOkxcFyMFCuqs3/NvOqevEk=
  on:
    branch: release
  skip_cleanup: true

notifications:
  email: false
